default_language_version:
  python: python3.12

repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
        exclude: 'tsconfig\.json'
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  # Ruff linting and formatting for backend
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        name: ruff (backend)
        args: [--config, backend/pyproject.toml]
        files: ^backend/
      - id: ruff-format
        name: ruff-format (backend)
        args: [--config, backend/pyproject.toml]
        files: ^backend/
