services:
  portal-frontend:
    image: ghcr.io/minbzk/bureaublad-frontend:dev
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_KEYCLOAK_URL: https://id.la-suite.apps.digilab.network/
        NEXT_PUBLIC_KEYCLOAK_REALM: lasuite
        NEXT_PUBLIC_KEYCLOAK_CLIENT: bureaublad-frontend
        NEXT_PUBLIC_BACKEND_BASE_URL: http://localhost:8080
    # env_file: frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - portal-backend
  portal-backend:
    image: ghcr.io/minbzk/bureaublad-api:dev
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8080:8080"
