services:
  bureaublad-frontend:
    image: ghcr.io/minbzk/bureaublad-frontend:dev
    build:
      context: frontend
      dockerfile: Dockerfile
      args: #todo: move these options to the backend
        NEXT_PUBLIC_KEYCLOAK_URL: http://localhost:8081
        NEXT_PUBLIC_KEYCLOAK_REALM: master
        NEXT_PUBLIC_KEYCLOAK_CLIENT: bureaublad-frontend
        NEXT_PUBLIC_BACKEND_BASE_URL: http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - bureaublad-backend
      - keycloak
  bureaublad-backend:
    image: ghcr.io/minbzk/bureaublad-api:dev
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "8080:8080"
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8081:8080
    command: start-dev --import-realm
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import