name: Build Frontend container

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

env:
  IMAGE_NAME: 'bureaublad-frontend'
  URL: 'https://bureaublad.apps.digilab.network'
  NEXT_PUBLIC_KEYCLOAK_URL: 'https://bureaublad.apps.digilab.network'
  NEXT_PUBLIC_KEYCLOAK_REALM: lasuite
  NEXT_PUBLIC_KEYCLOAK_CLIENT: bureaublad-frontend
  NEXT_PUBLIC_BACKEND_BASE_URL: 'https://bureaublad.apps.digilab.network'

jobs:
  push_to_registries:
    name: Push Docker image to github registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/minbzk/${{ env.IMAGE_NAME }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@v6
        with:
          context: frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/amd64,linux/arm64
          build-args: BACKEND_BASE_URL=$BACKEND_BASE_URL
        env:
          BACKEND_BASE_URL: ${{ env.URL }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/minbzk/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true